"""Инлайн-клавиатуры. Раньше — один inline.py на 780 строк, теперь пакет.

Все имена собраны обратно сюда, поэтому `from bot.keyboards.inline import ...`
по всему проекту не изменился ни в одном файле. Префиксы callback_data живут
в prefixes.py — модули клавиатур тянут их оттуда, а не друг у друга.
"""
from __future__ import annotations

from bot.keyboards.inline.admin import (
    admin_panel_menu,
    admin_sub_give_kb,
    admin_sub_kb,
    admin_user_bypass_card_kb,
    admin_user_device_card_kb,
    admin_user_items_kb,
    audit_list_kb,
    back_to_panel,
    back_to_users_kb,
    broadcast_confirm_kb,
    broadcast_select_kb,
    broadcast_target_kb,
    cancel_to_sub_kb,
    user_card_kb,
    user_history_kb,
    user_wipe_confirm_kb,
    users_list_kb,
)
from bot.keyboards.inline.balance import (
    balance_kb,
    deposit_amounts_kb,
    deposit_methods_kb,
    extend_kb,
    invoice_kb,
    star_amounts_kb,
    star_invoice_kb,
    topup_kb,
)
from bot.keyboards.inline.devices import (
    back_to_devices_kb,
    config_format_kb,
    device_card_kb,
    device_created_kb,
    devices_list_kb,
    move_confirm_kb,
    move_pick_config_kb,
    move_pick_location_kb,
    move_pick_server_kb,
    subscription_kb,
)
from bot.keyboards.inline.install import (
    cancel_only,
    install_auth_method,
    install_confirm,
)
from bot.keyboards.inline.legal import consent_kb
from bot.keyboards.inline.menu import (
    back_to_menu,
    main_menu,
    notify_settings_kb,
    onboarding_hint_kb,
    to_server,
)
from bot.keyboards.inline.prefixes import (
    CB_ADMIN,
    CB_BAL,
    CB_CANCEL,
    CB_CFG,
    CB_DEVICE,
    CB_INSTALL,
    CB_INVITES,
    CB_LEGAL,
    CB_MENU,
    CB_NOP,
    CB_PANEL,
    CB_SERVERS,
    CB_SUB,
    CB_SUPPORT,
    CB_WDTT,
)
from bot.keyboards.inline.servers import (
    admin_peer_card,
    back_to_servers_kb,
    confirm_delete_server,
    invite_card_kb,
    invites_list_kb,
    location_choice_kb,
    pick_location_kb,
    pick_server,
    server_card,
    server_peers_admin,
    server_wdtt_card_kb,
    server_wdtt_list_kb,
    servers_list,
    stats_nav,
    traffic_nav,
)
from bot.keyboards.inline.support import support_dialog_kb, support_intro_kb
from bot.keyboards.inline.wdtt import (
    back_to_bypasses_kb,
    wdtt_pick_device_kb,
    wdtt_platform_kb,
    wdtt_user_card_kb,
    wdtt_user_list_kb,
    wdtt_vk_choice_kb,
)

__all__ = [
    "CB_ADMIN",
    "CB_BAL",
    "CB_CANCEL",
    "CB_CFG",
    "CB_DEVICE",
    "CB_INSTALL",
    "CB_INVITES",
    "CB_LEGAL",
    "CB_MENU",
    "CB_NOP",
    "CB_PANEL",
    "CB_SERVERS",
    "CB_SUB",
    "CB_SUPPORT",
    "CB_WDTT",
    "admin_panel_menu",
    "admin_peer_card",
    "admin_sub_give_kb",
    "admin_sub_kb",
    "admin_user_bypass_card_kb",
    "admin_user_device_card_kb",
    "admin_user_items_kb",
    "audit_list_kb",
    "back_to_bypasses_kb",
    "back_to_devices_kb",
    "back_to_menu",
    "back_to_panel",
    "back_to_servers_kb",
    "back_to_users_kb",
    "balance_kb",
    "broadcast_confirm_kb",
    "broadcast_select_kb",
    "broadcast_target_kb",
    "cancel_only",
    "cancel_to_sub_kb",
    "confirm_delete_server",
    "config_format_kb",
    "consent_kb",
    "deposit_amounts_kb",
    "deposit_methods_kb",
    "device_card_kb",
    "device_created_kb",
    "devices_list_kb",
    "extend_kb",
    "install_auth_method",
    "install_confirm",
    "invite_card_kb",
    "invites_list_kb",
    "invoice_kb",
    "location_choice_kb",
    "main_menu",
    "move_confirm_kb",
    "move_pick_config_kb",
    "move_pick_location_kb",
    "move_pick_server_kb",
    "notify_settings_kb",
    "onboarding_hint_kb",
    "pick_location_kb",
    "pick_server",
    "server_card",
    "server_peers_admin",
    "server_wdtt_card_kb",
    "server_wdtt_list_kb",
    "servers_list",
    "star_amounts_kb",
    "star_invoice_kb",
    "stats_nav",
    "subscription_kb",
    "support_dialog_kb",
    "support_intro_kb",
    "to_server",
    "topup_kb",
    "traffic_nav",
    "user_card_kb",
    "user_history_kb",
    "user_wipe_confirm_kb",
    "users_list_kb",
    "wdtt_pick_device_kb",
    "wdtt_platform_kb",
    "wdtt_user_card_kb",
    "wdtt_user_list_kb",
    "wdtt_vk_choice_kb",
]
